export class Constance {
  static array: Array<String> = [
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "http://cloud.staging.p1.cn/v2/group-images/eyJpZCI6IlZDSTZIVkJUQVJJUVdFQjVLTFNHN0k2QUVTSUZJNiIsInciOjEwODAsImgiOjE0NDAsImQiOjAsIm10IjoiaW1hZ2UvanBlZyIsImRoIjoxNjQ4OTEzMjcwMjIxMzc2NTQ5N30",
    "http://cloud.staging.p1.cn/v2/group-images/eyJpZCI6IkVVVUdNUk9YNUdaS1dBVklSSjNNQU83SEZZRk00QyIsInciOjEwODAsImgiOjE0NDAsImQiOjAsIm10IjoiaW1hZ2UvanBlZyIsImRoIjo2Mzc0MjU0MzE3OTA2MjM3OTc4fQ",
    "http://cloud.staging.p1.cn/v2/group-images/eyJpZCI6IjNWU05HSDdUM1NaQVdBVjdRNjZVVkwyTlc2SEk2RyIsInciOjgyOCwiaCI6MTc5MiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjU1MDcxNTMyMjE3OTM5NDU4NjB9",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "https://s1.qianshouapp.cn/v2/group-images/eyJpZCI6IjRLN09GSkYzUU1YRlVXWEhOV0lESDJNSVZCSzdCQjA5IiwidyI6MTA3OSwiaCI6MTQ0NiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjUxOTkwODE5Mjg1MDQyMjY5MTh9.jpg?format=max_960xX_p3",
    "http://cloud.staging.p1.cn/v2/group-images/eyJpZCI6IlZDSTZIVkJUQVJJUVdFQjVLTFNHN0k2QUVTSUZJNiIsInciOjEwODAsImgiOjE0NDAsImQiOjAsIm10IjoiaW1hZ2UvanBlZyIsImRoIjoxNjQ4OTEzMjcwMjIxMzc2NTQ5N30",
    "http://cloud.staging.p1.cn/v2/group-images/eyJpZCI6IkVVVUdNUk9YNUdaS1dBVklSSjNNQU83SEZZRk00QyIsInciOjEwODAsImgiOjE0NDAsImQiOjAsIm10IjoiaW1hZ2UvanBlZyIsImRoIjo2Mzc0MjU0MzE3OTA2MjM3OTc4fQ",
    "http://cloud.staging.p1.cn/v2/group-images/eyJpZCI6IjNWU05HSDdUM1NaQVdBVjdRNjZVVkwyTlc2SEk2RyIsInciOjgyOCwiaCI6MTc5MiwiZCI6MCwibXQiOiJpbWFnZS9qcGVnIiwiZGgiOjU1MDcxNTMyMjE3OTM5NDU4NjB9",
  ]

  static arrays: Array<String> = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
  ]
}